#!/bin/bash

function createAllStar(){
    echo 'Enrolling the CA of Parent club'
    mkdir -p organizations/peerOrganizations/allStar.club.com/
    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/allStar.club.com/
    set -x
    fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-allStar --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
    { set +x; } 2>/dev/null
      echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-allStar.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-allStar.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-allStar.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-allStar.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/config.yaml"
     # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy allStar's CA cert to allStar's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/tlscacerts/ca.crt"

  # Copy allStar's CA cert to allStar's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStar.club.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStar.club.com/tlsca/tlsca.allStar.club.com-cert.pem"

  # Copy allStar's CA cert to allStar's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStar.club.com/ca"
  cp "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStar.club.com/ca/ca.allStar.club.com-cert.pem"

  # Registering peer0
echo "Registering peer0"
set -x
fabric-ca-client register --caname ca-allStar --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

# Registering peer1
echo "Registering peer1"
set -x
fabric-ca-client register --caname ca-allStar --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

# Registering user
echo "Registering user"
set -x
fabric-ca-client register --caname ca-allStar --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

# Registering the org admin
echo "Registering the org admin"
set -x
fabric-ca-client register --caname ca-allStar --id.name allStaradmin --id.secret allStaradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

# Generating the peer0 msp
echo "Generating the peer0 msp"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/msp/config.yaml"

# Generating the peer0-tls certificates
echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls" --enrollment.profile tls --csr.hosts peer0.allStar.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

# Now for peer1
# Generating the peer1 msp
echo "Generating the peer1 msp"
set -x
fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/msp/config.yaml"

# Generating the peer1-tls certificates
echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
set -x
fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls" --enrollment.profile tls --csr.hosts peer1.allStar.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

 # Copy the tls CA cert, server cert, server keystore to well-known file names in peer0's tls directory
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/ca.crt"
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/server.crt"
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer0.allStar.club.com/tls/server.key"

# For peer1
# Copy the tls CA cert, server cert, server keystore to well-known file names in peer1's tls directory
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/ca.crt"
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/server.crt"
cp "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/allStar.club.com/peers/peer1.allStar.club.com/tls/server.key"

# Generating the user msp
echo "Generating the user msp"
set -x
fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/users/User1@allStar.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStar.club.com/users/User1@allStar.club.com/msp/config.yaml"

# Generating the org admin msp
echo "Generating the org admin msp"
set -x
fabric-ca-client enroll -u https://allStaradmin:allStaradminpw@localhost:7054 --caname ca-allStar -M "${PWD}/organizations/peerOrganizations/allStar.club.com/users/Admin@allStar.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStar/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/allStar.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStar.club.com/users/Admin@allStar.club.com/msp/config.yaml"

}

function createAllStarAfrica() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/allStarAfrica.club.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:6054 --caname ca-allStarAfrica --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-allStarAfrica.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-allStarAfrica.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-allStarAfrica.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-allStarAfrica.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/config.yaml"
      # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy allStarAfrica's CA cert to allStarAfrica's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/tlscacerts/ca.crt"

  # Copy allStarAfrica's CA cert to allStarAfrica's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/tlsca/tlsca.allStarAfrica.club.com-cert.pem"

  # Copy allStarAfrica's CA cert to allStarAfrica's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/ca"
  cp "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/ca/ca.allStarAfrica.club.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-allStarAfrica --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-allStarAfrica --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-allStarAfrica --id.name allStarAfricaadmin --id.secret allStarAfricaadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-allStarAfrica -M "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-allStarAfrica -M "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls" --enrollment.profile tls --csr.hosts peer0.allStarAfrica.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null


  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/peers/peer0.allStarAfrica.club.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:6054 --caname ca-allStarAfrica -M "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/users/User1@allStarAfrica.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/users/User1@allStarAfrica.club.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://dealeradmin:dealeradminpw@localhost:6054 --caname ca-allStarAfrica -M "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/users/Admin@allStarAfrica.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAfrica/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAfrica.club.com/users/Admin@allStarAfrica.club.com/msp/config.yaml"
}

function createAllStarAsia() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/allStarAsia.club.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/allStarAsia.club.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-allStarAsia --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-allStarAsia.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-allStarAsia.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-allStarAsia.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-allStarAsia.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy allStarAsia's CA cert to allStarAsia's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/tlscacerts/ca.crt"

  # Copy allStarAsia's CA cert to allStarAsia's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/tlsca/tlsca.allStarAsia.club.com-cert.pem"

  # Copy allStarAsia's CA cert to allStarAsia's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/ca"
  cp "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/ca/ca.allStarAsia.club.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-allStarAsia --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-allStarAsia --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-allStarAsia --id.name allStarAsiaadmin --id.secret allStarAsiaadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-allStarAsia -M "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-allStarAsia -M "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls" --enrollment.profile tls --csr.hosts peer0.allStarAsia.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/peers/peer0.allStarAsia.club.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-allStarAsia -M "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/users/User1@allStarAsia.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/users/User1@allStarAsia.club.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://mvdadmin:mvdadminpw@localhost:8054 --caname ca-allStarAsia -M "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/users/Admin@allStarAsia.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/allStarAsia/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/allStarAsia.club.com/users/Admin@allStarAsia.club.com/msp/config.yaml"
}

function createFootballAssociation() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/footballAssociation.club.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/footballAssociation.club.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:5054 --caname ca-footballAssociation --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-footballAssociation.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-footballAssociation.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-footballAssociation.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-footballAssociation.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy footballAssociation's CA cert to footballAssociation's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/tlscacerts/ca.crt"

  # Copy footballAssociation's CA cert to footballAssociation's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/tlsca/tlsca.footballAssociation.club.com-cert.pem"

  # Copy footballAssociation's CA cert to footballAssociation's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/ca"
  cp "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/ca/ca.footballAssociation.club.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-footballAssociation --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-footballAssociation --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-footballAssociation --id.name footballAssociationadmin --id.secret footballAssociationadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5054 --caname ca-footballAssociation -M "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5054 --caname ca-footballAssociation -M "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls" --enrollment.profile tls --csr.hosts peer0.footballAssociation.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/peers/peer0.footballAssociation.club.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:5054 --caname ca-footballAssociation -M "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/users/User1@footballAssociation.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/users/User1@footballAssociation.club.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://mvdadmin:mvdadminpw@localhost:5054 --caname ca-footballAssociation -M "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/users/Admin@footballAssociation.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/footballAssociation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/footballAssociation.club.com/users/Admin@footballAssociation.club.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/club.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/club.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:5054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-5054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/club.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/club.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/club.com/msp/tlscacerts/tlsca.club.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/club.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/club.com/tlsca/tlsca.club.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:5054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/club.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:5054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls" --enrollment.profile tls --csr.hosts orderer.club.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/club.com/orderers/orderer.club.com/msp/tlscacerts/tlsca.club.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:5054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/club.com/users/Admin@club.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/club.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/club.com/users/Admin@club.com/msp/config.yaml"
}
createAllStar
createAllStarAfrica
createAllStarAsia
createFootballAssociation
createOrderer
